FROM openjdk:8-jdk-alpine
FROM envoyproxy/envoy-dev:latest

ARG JAR_FILE=build/libs/*.jar
ADD ${JAR_FILE} app.jar

ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh