#! /bin/bash

PWD=`pwd`
echo ${PWD}

case $1 in
    "py")
        echo "envoy python"
        case $2 in
            "down")
                echo "down..."
                cd envoy-python && docker-compose down
            ;;
            "up")
                echo "up..."
                cd envoy-python && docker-compose up --build -d
            ;;
        esac
    ;;
    "java")
        echo "envoy java"
        case $2 in
            "down")
                echo "down..."
                cd envoy-java/deploy && docker-compose down
            ;;
            "up")
                echo "up..."
                cd envoy-java/deploy && docker-compose up --build -d
            ;;
            "scale")
                echo "scale..."
                cd envoy-java/deploy && docker-compose scale $3=$4
            ;;
        esac
    ;;
esac
