#! /bin/bash

PWD=`pwd`
echo ${PWD}

case $1 in
    "python")
        echo "start envoy web"
        cd envoy-web/deploy/local && docker-compose down && docker-compose up -d
    ;;
    "java")
        echo "start envoy server"
        cd envoy-server/deploy/local && docker-compose down && docker-compose up -d
    ;;
esac
